services:
  php:
    image: oboumediane/tutoring-app-php:latest
    pull_policy: always

    # build:
    #   context: .
    #   dockerfile: Dockerfile

    container_name: tutoring-php
    restart: unless-stopped
    env_file:
      - .env.prod
    depends_on:
      - postgres
    networks:
      - tutoring

  nginx:
    image: oboumediane/tutoring-app-nginx:latest
    pull_policy: always

#    build:
#      context: .
#      dockerfile: nginx.Dockerfile

    container_name: tutoring-nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    depends_on:
      - php
    networks:
      - tutoring

  postgres:
    image: postgres:18
    container_name: tutoring-db
    restart: unless-stopped
    env_file:
      - .env.prod
    environment:
      - POSTGRES_DB=${DB_DATABASE}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - "6543:5432"
    volumes:
      - postgres-data:/var/lib/postgresql
    networks:
      - tutoring

  grafana:
    image: grafana/grafana-enterprise
    container_name: grafana
    restart: unless-stopped
    ports:
      - '3000:3000'
    volumes:
      - grafana-storage:/var/lib/grafana

networks:
  tutoring:
    driver: bridge

volumes:
  postgres-data:
  grafana-storage:
